version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    stop_signal: SIGINT
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
