version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "8080:80"
